---
version: '3.7'
services:

  db:
    image: mysql:8.0
    command: '--default-authentication-plugin=mysql_native_password'
    volumes:
      - ./data/mariadb:/var/lib/mysql
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=Passw0rd
      - MYSQL_ROOT_HOST=%
      - MYSQL_DATABASE=exampledb
      - MYSQL_USER=grafana
      - MYSQL_PASSWORD=Passw0rd
    ports:
      - 3306:3306
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:

